### ISSUE TITLE
TypeError: _DecoratorContextManager.clone() got an unexpected keyword argument 'attention_mask'

### ISSUE THREAD

**Issue by zhaijianyang** [agiresearch/IDGenRec#2]
Hello，
i got error, how to solve it?

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/userhome/projects/IDGenRec/src/main_generative.py", line 119, in distributed_main
    runner.train_generator()
  File "/userhome/projects/IDGenRec/src/runner/DistributedRunner_gen.py", line 160, in train_generator
    output = self.model_gen.module.generate_with_grad(
TypeError: _DecoratorContextManager.clone() got an unexpected keyword argument 'attention_mask'

**Comment by Maribel-Hearn** [comment]
你好，请问你那边解决了这个问题吗？我这里也遇到了同样的问题没办法解决

**Comment by wulongfeng** [comment]
Hello, I'm experiencing the same issue. Do you have any suggestions? Thank you!
I think it may be caused by the library version, but I am not sure which version should be installed.

**Comment by wulongfeng** [comment]
> Hello, I'm experiencing the same issue. Do you have any suggestions? Thank you! I think it may be caused by the library version, but I am not sure which version should be installed.

Resolved this issue by upgrading torch to `torch==1.11.0+cu113`.

**Comment by pkuwsh** [comment]
> > Hello, I'm experiencing the same issue. Do you have any suggestions? Thank you! I think it may be caused by the library version, but I am not sure which version should be installed.
> 
> Resolved this issue by upgrading torch to `torch==1.11.0+cu113`.

I got the same issue with transformers==4.26.0 and torch=={2.0.1, 1.11.0, 1.8.1}. Could u show your dependency list, thx so much.

**Comment by pkuwsh** [comment]
> > > Hello, I'm experiencing the same issue. Do you have any suggestions? Thank you! I think it may be caused by the library version, but I am not sure which version should be installed.
> > 
> > 
> > Resolved this issue by upgrading torch to `torch==1.11.0+cu113`.
> 
> I got the same issue with transformers==4.26.0 and torch=={2.0.1, 1.11.0, 1.8.1}. Could u show your dependency list, thx so much.

Resolved this issue. I guess something went wrong when using `undecorated`  to enable `model_gen.generate()` to compute with gradients. So I replace `output = self.model_gen.module.generate_with_grad` with `output = self.model_gen.module.generate.__wrapped__`. More details about this issue can be found at [https://discuss.huggingface.co/t/how-to-output-loss-from-model-generate/16999/12](url).

My libary versions: torch==2.0.1, transformers==4.25.1.
